obstacles:
- name: box_1
  type: box
  color: red
  enabled: true
  x_pose: -6.9
  y_pose: 19.6
  z_pose: 0.5
  size: [0.5, 0.5, 1.0]
  motion:
    type: linear
    velocity: 0.5
    std: 0.0
    path:
    - [0.0, 0.0]
    - [0.0, 1.2999999999999972]
- name: box_2
  type: box
  color: green
  enabled: true
  x_pose: 11.0
  y_pose: -14.9
  z_pose: 0.5
  size: [0.5, 0.5, 1.0]
  motion:
    type: linear
    velocity: 0.5
    std: 0.0
    path:
    - [0.0, 0.0]
    - [-1.6999999999999993, 0.0]
