obstacles:
- name: box_1
  type: box
  color: gray
  enabled: true
  x_pose: 13.2
  y_pose: 1.4
  z_pose: 0.5
  size: [0.5, 0.5, 1.0]
  motion:
    type: linear
    velocity: 1.0
    std: 0.0
    path:
    - [13.2, 1.5]
    - [22.6, 1.3]
- name: box_2
  type: box
  color: red
  enabled: true
  x_pose: 45.3
  y_pose: 46.8
  z_pose: 0.5
  size: [1.0, 1.0, 1.0]
  motion:
    type: linear
    velocity: 1.0
    std: 0.0
    path:
    - [45.2, 46.9]
    - [27.9, 46.9]
